In [1]:
# @hidden_cell
# The project token is an authorization token that is used to access project resources like data sources, connections, and used by platform APIs.
from project_lib import Project
project = Project(project_id='535e152e-5729-4964-9191-6c31b859ebc0', project_access_token='p-2+9qO7dze5M2ojjfMR/Nr26g==;FJGxGKnK7gp5ALZpkzgveQ==:Sk6MPMAN0GDJyRlA7V/dGqGG2yyxv49S3fcQxkZYoBfAAtNACF1Yc5EzO3zoszzhrawvxftCcY8X9o2bxoZYBWgZc+qcCqCyPQ==')
pc = project.project_context

from ibm_watson_studio_lib import access_project_or_space
wslib = access_project_or_space({'token':'p-2+9qO7dze5M2ojjfMR/Nr26g==;FJGxGKnK7gp5ALZpkzgveQ==:Sk6MPMAN0GDJyRlA7V/dGqGG2yyxv49S3fcQxkZYoBfAAtNACF1Yc5EzO3zoszzhrawvxftCcY8X9o2bxoZYBWgZc+qcCqCyPQ=='})

In [2]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='LcyS2t8qRdTQ1ket25gYggmKTGFhQ85mspd0bjMLfF3k',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/identity/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.direct.us-south.cloud-object-storage.appdomain.cloud')

bucket = 'sandboxproject-donotdelete-pr-snjjamdlq8h7ju'
object_key = 'player_profiles.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

players = pd.read_csv(body)
players.head(10)

/tmp/wsuser/ipykernel_354/1045735673.py:25: DtypeWarning: Columns (29,30,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv(body)

,player_id,player_slug,player_name,player_image_url,name_in_home_country,date_of_birth,place_of_birth,country_of_birth,height,citizenship,...,on_loan_from_club_id,on_loan_from_club_name,contract_there_expires,second_club_url,second_club_name,third_club_url,third_club_name,fourth_club_url,fourth_club_name,date_of_death
0,1,silvio-adzic,Silvio Adzic (1),https://img.a.transfermarkt.technology/portrai...,NaN,1980-09-23,Grünstadt,Germany,0.0,Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100011,everton-silva,Éverton Silva (100011),https://img.a.transfermarkt.technology/portrai...,Éverton José Modesto da Silva,1988-08-04,São João de Meriti,Brazil,171.0,Brazil,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10001,john-thompson,John Thompson (10001),https://img.a.transfermarkt.technology/portrai...,John Paul Thompson,1981-10-12,Dublin,Ireland,183.0,Ireland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100001,carlos-auzqui,Carlos Auzqui (100001),https://img.a.transfermarkt.technology/portrai...,Carlos Daniel Auzqui,1991-03-16,Longchamps,Argentina,180.0,Argentina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1000152,sodick-adejumo,Sodick Adejumo (1000152),https://img.a.transfermarkt.technology/portrai...,NaN,2004-01-08,Saint-Denis,France,198.0,France Nigeria,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1000153,matheo-sanchez,Matheo Sánchez (1000153),https://img.a.transfermarkt.technology/portrai...,Matheo Manuel André Sánchez,2003-03-13,Belfort,France,186.0,France,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,10002,brian-cash,Brian Cash (10002),https://img.a.transfermarkt.technology/portrai...,NaN,1982-11-24,Dublin,Ireland,175.0,Ireland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,100020,sergiy-zagynaylov,Sergiy Zagynaylov (100020),https://img.a.transfermarkt.technology/portrai...,Загинайлов Сергій Геннадійович,1991-01-03,"Brovary, Kyiv Oblast",Ukraine,181.0,Ukraine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1000161,lenny-stoltz,Lenny Stoltz (1000161),https://img.a.transfermarkt.technology/portrai...,Lenny Stoltz Kachouri,2000-06-13,Wissembourg,France,182.0,France Tunisia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='LcyS2t8qRdTQ1ket25gYggmKTGFhQ85mspd0bjMLfF3k',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/identity/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.direct.us-south.cloud-object-storage.appdomain.cloud')

bucket = 'sandboxproject-donotdelete-pr-snjjamdlq8h7ju'
object_key = 'player_injuries.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

injuries = pd.read_csv(body)
injuries.head(10)

,player_id,season_name,injury_reason,from_date,end_date,days_missed,games_missed
0,10,15/16,Hand injury,2016-04-19,2016-04-29,11.0,2
1,10,15/16,Thigh problems,2015-12-18,2015-12-31,14.0,1
2,10,15/16,Capsular injury,2015-11-11,2015-11-21,11.0,0
3,10,15/16,Rest,2015-11-04,2015-11-06,3.0,1
4,10,15/16,Hamstring injury,2015-08-20,2015-10-08,50.0,10
5,10,14/15,Lumbago,2014-12-02,2014-12-04,3.0,1
6,10,13/14,muscular problems,2014-04-06,2014-05-03,28.0,4
7,10,13/14,Back problems,2014-03-23,2014-03-29,7.0,2
8,10,13/14,Pelvic injury,2014-02-27,2014-03-05,7.0,3
9,10,13/14,cold,2014-01-27,2014-02-01,6.0,1

In [4]:
# Joining two DataFrames
players_and_injuries = pd.merge(players, injuries, on='player_id')
players_and_injuries.head(10)

,player_id,player_slug,player_name,player_image_url,name_in_home_country,date_of_birth,place_of_birth,country_of_birth,height,citizenship,...,third_club_name,fourth_club_url,fourth_club_name,date_of_death,season_name,injury_reason,from_date,end_date,days_missed,games_missed
0,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,15/16,Hand injury,2016-04-19,2016-04-29,11.0,2
1,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,15/16,Thigh problems,2015-12-18,2015-12-31,14.0,1
2,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,15/16,Capsular injury,2015-11-11,2015-11-21,11.0,0
3,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,15/16,Rest,2015-11-04,2015-11-06,3.0,1
4,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,15/16,Hamstring injury,2015-08-20,2015-10-08,50.0,10
5,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,14/15,Lumbago,2014-12-02,2014-12-04,3.0,1
6,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,13/14,muscular problems,2014-04-06,2014-05-03,28.0,4
7,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,13/14,Back problems,2014-03-23,2014-03-29,7.0,2
8,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,13/14,Pelvic injury,2014-02-27,2014-03-05,7.0,3
9,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,13/14,cold,2014-01-27,2014-02-01,6.0,1

In [5]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='LcyS2t8qRdTQ1ket25gYggmKTGFhQ85mspd0bjMLfF3k',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/identity/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.direct.us-south.cloud-object-storage.appdomain.cloud')

bucket = 'sandboxproject-donotdelete-pr-snjjamdlq8h7ju'
object_key = 'team_details.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

teams = pd.read_csv(body)
teams.head(10)

,club_id,club_slug,club_name,logo_url,country_name,season_id,competition_id,competition_slug,competition_name,club_division,source_url,_last_modified_at
0,100335,cd-mafra-sub-23,CD Mafra U23 (100335),https://tmssl.akamaized.net//images/wappen/hea...,Portugal,2023,NaN,NaN,NaN,NaN,https://www.transfermarkt.com/cd-mafra-sub-23/...,2025-09-11 20:20:19
1,100431,napoli-under-18,Napoli Under 18 (100431),https://tmssl.akamaized.net//images/wappen/hea...,Italy,2021,ITJ7,campionato-nazionale-under-18,Campionato Under 18,Campionato Under 18,https://www.transfermarkt.com/napoli-under-18/...,2025-09-13 09:55:03
2,101416,venezia-under-18,Venezia Under 18 (101416),https://tmssl.akamaized.net//images/wappen/hea...,Italy,2022,NaN,NaN,NaN,NaN,https://www.transfermarkt.com/venezia-under-18...,2025-09-13 09:37:05
3,100461,lecce-under-18,Lecce Under 18 (100461),https://tmssl.akamaized.net//images/wappen/hea...,Italy,2015,ITJ7,campionato-nazionale-under-18,Campionato Under 18,Campionato Under 18,https://www.transfermarkt.com/lecce-under-18/s...,2025-09-13 09:52:59
4,10010,esporte-clube-bahia,Esporte Clube Bahia (10010),https://tmssl.akamaized.net//images/wappen/hea...,Brazil,2006,BRA1,campeonato-brasileiro-serie-a,Campeonato Brasileiro Série A,Campeonato Brasileiro Série A,https://www.transfermarkt.com/esporte-clube-ba...,2025-09-13 11:59:31
5,101282,charlotte-fc-mls-next-pro,Crown Legacy FC (101282),https://tmssl.akamaized.net//images/wappen/hea...,United States,2021,MNP3,mls-next-pro,MLS Next Pro,MLS Next Pro,https://www.transfermarkt.com/charlotte-fc-mls...,2025-09-13 13:01:28
6,1,1-fc-saarbrucken,1.FC Saarbrücken (1),https://tmssl.akamaized.net//images/wappen/hea...,Germany,2002,L3,3-liga,3. Liga,3. Liga,https://www.transfermarkt.com/1-fc-saarbrucken...,2025-09-13 10:41:56
7,10,arminia-bielefeld,Arminia Bielefeld (10),https://tmssl.akamaized.net//images/wappen/hea...,Germany,2008,L2,2-bundesliga,2. Bundesliga,2. Bundesliga,https://www.transfermarkt.com/arminia-bielefel...,2025-09-13 09:26:57
8,100330,sudtirol-under-17,Südtirol Under 17 (100330),https://tmssl.akamaized.net//images/wappen/hea...,Italy,2013,ITJ5,campionato-nazionale-under-17-b,Campionato nazionale Under 17 - B,Campionato nazionale Under 17 - B,https://www.transfermarkt.com/sudtirol-under-1...,2025-09-13 10:09:44
9,1022,cerezo-osaka,Cerezo Osaka (1022),https://tmssl.akamaized.net//images/wappen/hea...,Japan,2017,JAP1,j1-league,J1 League,J1 League,https://www.transfermarkt.com/cerezo-osaka/sta...,2025-09-13 11:12:23

In [6]:
print(teams.columns.tolist())

['club_id', 'club_slug', 'club_name', 'logo_url', 'country_name', 'season_id', 'competition_id', 'competition_slug', 'competition_name', 'club_division', 'source_url', '_last_modified_at']

In [7]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='LcyS2t8qRdTQ1ket25gYggmKTGFhQ85mspd0bjMLfF3k',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/identity/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.direct.us-south.cloud-object-storage.appdomain.cloud')

bucket = 'sandboxproject-donotdelete-pr-snjjamdlq8h7ju'
object_key = 'player_latest_market_value.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

player_values = pd.read_csv(body)
player_values.head(10)

   player_id   date_unix  value
0          1  2009-04-22    0.0
1          6  2010-08-01    0.0
2          8  2010-01-01    0.0
3         10  2016-06-30    0.0
4         11  2009-03-18    0.0
5         16  2009-02-09    0.0
6         17  2006-06-30    0.0
7         18  2005-12-31    0.0
8         27  2006-06-30    0.0
9         39  2010-07-01    0.0

In [8]:
players_merged_values = pd.merge(
    players, 
    player_values, 
    on='player_id',
    how='left'
)

players_merged_values.head(10)

,player_id,player_slug,player_name,player_image_url,name_in_home_country,date_of_birth,place_of_birth,country_of_birth,height,citizenship,...,contract_there_expires,second_club_url,second_club_name,third_club_url,third_club_name,fourth_club_url,fourth_club_name,date_of_death,date_unix,value
0,1,silvio-adzic,Silvio Adzic (1),https://img.a.transfermarkt.technology/portrai...,NaN,1980-09-23,Grünstadt,Germany,0.0,Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-04-22,0.0
1,100011,everton-silva,Éverton Silva (100011),https://img.a.transfermarkt.technology/portrai...,Éverton José Modesto da Silva,1988-08-04,São João de Meriti,Brazil,171.0,Brazil,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-10-31,0.0
2,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-06-30,0.0
3,10001,john-thompson,John Thompson (10001),https://img.a.transfermarkt.technology/portrai...,John Paul Thompson,1981-10-12,Dublin,Ireland,183.0,Ireland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-06-30,0.0
4,100001,carlos-auzqui,Carlos Auzqui (100001),https://img.a.transfermarkt.technology/portrai...,Carlos Daniel Auzqui,1991-03-16,Longchamps,Argentina,180.0,Argentina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-06-01,200000.0
5,1000152,sodick-adejumo,Sodick Adejumo (1000152),https://img.a.transfermarkt.technology/portrai...,NaN,2004-01-08,Saint-Denis,France,198.0,France Nigeria,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1000153,matheo-sanchez,Matheo Sánchez (1000153),https://img.a.transfermarkt.technology/portrai...,Matheo Manuel André Sánchez,2003-03-13,Belfort,France,186.0,France,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,10002,brian-cash,Brian Cash (10002),https://img.a.transfermarkt.technology/portrai...,NaN,1982-11-24,Dublin,Ireland,175.0,Ireland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-05-25,0.0
8,100020,sergiy-zagynaylov,Sergiy Zagynaylov (100020),https://img.a.transfermarkt.technology/portrai...,Загинайлов Сергій Геннадійович,1991-01-03,"Brovary, Kyiv Oblast",Ukraine,181.0,Ukraine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-05,0.0
9,1000161,lenny-stoltz,Lenny Stoltz (1000161),https://img.a.transfermarkt.technology/portrai...,Lenny Stoltz Kachouri,2000-06-13,Wissembourg,France,182.0,France Tunisia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-06,0.0

In [15]:

# 1. Convert the 'date_of_birth' column to datetime objects
# errors='coerce' will turn invalid dates into NaT (Not a Time) instead of crashing
players_merged_values['date_of_birth'] = pd.to_datetime(players_merged_values['date_of_birth'], errors='coerce')

# 2. Get today's date (or set a specific date like the World Cup start)
now = pd.Timestamp.now()

# 3. Calculate age
# We subtract the dates to get 'Timedeltas', then convert to days and divide by 365.25
players_merged_values['age'] = (now - players_merged_values['date_of_birth']).dt.days / 365.25

# 4. Optional: Round down to the nearest whole number
players_merged_values['age'] = players_merged_values['age'].fillna(0).astype(int)

print(players_merged_values[['player_name', 'date_of_birth', 'age']].head())

              player_name date_of_birth  age
0        Silvio Adzic (1)    1980-09-23   45
1  Éverton Silva (100011)    1988-08-04   37
2     Miroslav Klose (10)    1978-06-09   47
3   John Thompson (10001)    1981-10-12   44
4  Carlos Auzqui (100001)    1991-03-16   35

In [16]:
# Merge them (Left Join keeps all players)
# This results in one big table with player names, values, and their club names
df_complete = pd.merge(
    players_merged_values, 
    teams[['club_id', 'club_name', 'competition_id', 'club_division']], 
    left_on='current_club_id', 
    right_on='club_id', 
    how='left'
)

# Create the National Team Power Ranking
# We group by the player's country and sum their market values
world_cup_ranking = df_complete.groupby('citizenship')['value'].sum().reset_index()

# Sort to see the top contenders
world_cup_ranking = world_cup_ranking.sort_values(by='value', ascending=False)

# 3. Format the numbers to be more readable (in Millions)
world_cup_ranking['Value in Millions'] = world_cup_ranking['value'] / 1_000_000

# 3. Sort by the new 'Team Name' column
teams_current_sorted = df_complete.sort_values(by='club_name')

print(world_cup_ranking.head(10))

           citizenship         value  Value in Millions
2168             Spain  3.731125e+09          3731.1250
302             Brazil  3.370970e+09          3370.9700
751            England  2.383295e+09          2383.2950
1301             Italy  2.246725e+09          2246.7250
988            Germany  1.618450e+09          1618.4500
1904          Portugal  1.604738e+09          1604.7375
57           Argentina  1.040385e+09          1040.3850
1627       Netherlands  9.760100e+08           976.0100
75    Argentina  Italy  8.457000e+08           845.7000
1790            Norway  8.342500e+08           834.2500

In [17]:
wslib.save_data("teams_current_sorted.csv",teams_current_sorted.to_csv(index=False).encode(), overwrite=True)
wslib.save_data("world_cup_ranking.csv",world_cup_ranking.to_csv(index=False).encode(), overwrite=True)

{'name': 'world_cup_ranking.csv',
 'asset_type': 'data_asset',
 'asset_id': 'a8452a82-167e-42cd-a726-5905b2b6aa40',
 'attachment_id': 'dadb89df-e30c-4dc4-89b7-2d107aec61dc',
 'filepath': 'world_cup_ranking.csv',
 'data_size': 83029,
 'mime': 'text/csv',
 'summary': ['looked up asset',
  'selected attachment',
  'overwritten file',
  'updated attachment'],
 'access_count': 1}

In [18]:
def predict_match(team_a_name, team_b_name, ranking_df):
    # 1. Get the values for both teams
    try:
        val_a = ranking_df.loc[ranking_df['citizenship'] == team_a_name, 'value'].values[0]
        val_b = ranking_df.loc[ranking_df['citizenship'] == team_b_name, 'value'].values[0]
    except IndexError:
        return "One of the teams was not found in the dataset."

    # 2. Calculate the Ratio
    ratio = val_a / val_b if val_b > 0 else 100
    
    # 3. Assign Logic for Wins
    if ratio > 2.0:
        prediction = f"{team_a_name} is a Heavy Favorite"
        prob = "75-90%"
    elif 1.2 < ratio <= 2.0:
        prediction = f"{team_a_name} is the Favorite"
        prob = "60-70%"
    elif 0.8 <= ratio <= 1.2:
        prediction = "It's a Toss-up / Likely Draw"
        prob = "50/50"
    elif 0.5 <= ratio < 0.8:
        prediction = f"{team_b_name} is the Favorite"
        prob = "60-70%"
    else:
        prediction = f"{team_b_name} is a Heavy Favorite"
        prob = "75-90%"

    return f"Match: {team_a_name} vs {team_b_name} | Result: {prediction} (Confidence: {prob})"

# Example Usage:
result = predict_match('France', 'Morocco', world_cup_ranking)
print(result)

Match: France vs Morocco | Result: France is a Heavy Favorite (Confidence: 75-90%)

In [19]:
# List of fixtures
fixtures = [('France', 'Poland'), ('England', 'Senegal'), ('Argentina', 'Australia')]

for team_a, team_b in fixtures:
    print(predict_match(team_a, team_b, world_cup_ranking))

Match: France vs Poland | Result: France is the Favorite (Confidence: 60-70%)
Match: England vs Senegal | Result: England is a Heavy Favorite (Confidence: 75-90%)
Match: Argentina vs Australia | Result: Argentina is a Heavy Favorite (Confidence: 75-90%)

In [21]:
print(df_complete.columns.tolist())

['player_id', 'player_slug', 'player_name', 'player_image_url', 'name_in_home_country', 'date_of_birth', 'place_of_birth', 'country_of_birth', 'height', 'citizenship', 'is_eu', 'position', 'main_position', 'foot', 'current_club_id', 'current_club_name', 'joined', 'contract_expires', 'outfitter', 'social_media_url', 'player_agent_id', 'player_agent_name', 'contract_option', 'date_of_last_contract_extension', 'on_loan_from_club_id', 'on_loan_from_club_name', 'contract_there_expires', 'second_club_url', 'second_club_name', 'third_club_url', 'third_club_name', 'fourth_club_url', 'fourth_club_name', 'date_of_death', 'date_unix', 'value', 'age', 'club_id', 'club_name', 'competition_id', 'club_division']

In [20]:
print(df_complete)

       player_id       player_slug                player_name  \
0              1      silvio-adzic           Silvio Adzic (1)
1         100011     everton-silva     Éverton Silva (100011)
2             10    miroslav-klose        Miroslav Klose (10)
3          10001     john-thompson      John Thompson (10001)
4         100001     carlos-auzqui     Carlos Auzqui (100001)
...          ...               ...                        ...
92666       9999         dean-west           Dean West (9999)
92667     999859  giacomo-seminari  Giacomo Seminari (999859)
92668      99993  nicolas-mezquida   Nicolás Mezquida (99993)
92669     999860    michael-petito    Michael Petito (999860)
92670      99995      mehmet-yigit       Mehmet Yiğit (99995)

                                        player_image_url  \
0      https://img.a.transfermarkt.technology/portrai...
1      https://img.a.transfermarkt.technology/portrai...
2      https://img.a.transfermarkt.technology/portrai...
3      https://img.a.transfermarkt.technology/portrai...
4      https://img.a.transfermarkt.technology/portrai...
...                                                  ...
92666  https://img.a.transfermarkt.technology/portrai...
92667  https://img.a.transfermarkt.technology/portrai...
92668  https://img.a.transfermarkt.technology/portrai...
92669  https://img.a.transfermarkt.technology/portrai...
92670  https://img.a.transfermarkt.technology/portrai...

                name_in_home_country date_of_birth      place_of_birth  \
0                                NaN    1980-09-23           Grünstadt
1      Éverton José Modesto da Silva    1988-08-04  São João de Meriti
2               Miroslav Josef Klose    1978-06-09               Opole
3                 John Paul Thompson    1981-10-12              Dublin
4               Carlos Daniel Auzqui    1991-03-16          Longchamps
...                              ...           ...                 ...
92666                            NaN    1972-12-05           Wakefield
92667                            NaN    2006-01-15             Codogno
92668  Gabriel Nicolás Mezquida Sero    1992-01-21            Paysandú
92669                            NaN    2006-02-09                 NaN
92670                            NaN    1991-06-24           Gaziantep

      country_of_birth  height     citizenship  ...  fourth_club_url  \
0              Germany     0.0         Germany  ...              NaN
1               Brazil   171.0          Brazil  ...              NaN
2              Germany   184.0         Germany  ...              NaN
3              Ireland   183.0         Ireland  ...              NaN
4            Argentina   180.0       Argentina  ...              NaN
...                ...     ...             ...  ...              ...
92666          England   178.0         England  ...              NaN
92667            Italy   180.0           Italy  ...              NaN
92668          Uruguay   171.0  Uruguay  Italy  ...              NaN
92669              NaN     0.0           Italy  ...              NaN
92670          Türkiye   190.0         Türkiye  ...              NaN

      fourth_club_name date_of_death   date_unix     value age  club_id  \
0                  NaN           NaN  2009-04-22       0.0  45      NaN
1                  NaN           NaN  2023-10-31       0.0  37      NaN
2                  NaN           NaN  2016-06-30       0.0  47      NaN
3                  NaN           NaN  2013-06-30       0.0  44      NaN
4                  NaN           NaN  2025-06-01  200000.0  35  14554.0
...                ...           ...         ...       ...  ..      ...
92666              NaN           NaN  2013-02-18       0.0  53      NaN
92667              NaN           NaN  2025-06-26  125000.0  20  19114.0
92668              NaN           NaN  2025-05-11  125000.0  34      NaN
92669              NaN           NaN         NaN       NaN  20      NaN
92670              NaN           NaN  2024-09-26       0.0  34      NaN

                           club_name competition_id    club_division
0                                NaN            NaN              NaN
1                                NaN            NaN              NaN
2                                NaN            NaN              NaN
3                                NaN            NaN              NaN
4      Club Atlético Tucumán (14554)           ARGC  Torneo Clausura
...                              ...            ...              ...
92666                            NaN            NaN              NaN
92667     Sassuolo Primavera (19114)            IJ1      Primavera 1
92668                            NaN            NaN              NaN
92669                            NaN            NaN              NaN
92670                            NaN            NaN              NaN

[92671 rows x 41 columns]

In [22]:
# 1. Define the 'Big 5' League Names (Update these based on your team_details.csv)
# Usually identified by 'league_id' or 'domestic_league_id'
top_league_ids = ['GB1', 'ES1', 'L1', 'IT1', 'FR1'] 

# 2. Add 'is_top_league' flag to your merged dataset
df_complete['is_top_league'] = df_complete['competition_id'].isin(top_league_ids)

# 3. Aggregate Advanced Features by Country
advanced_stats = df_complete.groupby('citizenship').agg({
    'value': 'sum',
    'age': 'mean',
    'is_top_league': 'sum', # Counts how many players are in top leagues
    'player_id': 'count'    # Total squad size
}).reset_index()

# 4. Clean up columns and calculate 'Top League Ratio'
advanced_stats.columns = ['Country', 'Total Value', 'Avg Age', 'Top League Players', 'Squad Size']
advanced_stats['Top League Ratio'] = advanced_stats['Top League Players'] / advanced_stats['Squad Size']

# 5. Filter for teams with a realistic squad size (e.g., > 15 players)
world_cup_contenders = advanced_stats[advanced_stats['Squad Size'] >= 15].sort_values(by='Total Value', ascending=False)

print(world_cup_contenders.head(10))

               Country   Total Value    Avg Age  Top League Players  \
2168             Spain  3.731125e+09  32.532850                 309
302             Brazil  3.370970e+09  31.741247                  54
751            England  2.383295e+09  30.287098                 100
1301             Italy  2.246725e+09  27.722920                 174
988            Germany  1.618450e+09  31.239911                 158
1904          Portugal  1.604738e+09  30.069231                  36
57           Argentina  1.040385e+09  32.445369                  20
1627       Netherlands  9.760100e+08  30.468059                  33
75    Argentina  Italy  8.457000e+08  35.674897                  33
1790            Norway  8.342500e+08  27.804839                  24

      Squad Size  Top League Ratio
2168        5936          0.052055
302         5484          0.009847
751         4131          0.024207
1301       12574          0.013838
988         3147          0.050207
1904        2210          0.016290
57          1922          0.010406
1627        1628          0.020270
75           729          0.045267
1790         620          0.038710

In [23]:
wslib.save_data("world_cup_training_data.csv",df_complete.to_csv(index=False).encode(), overwrite=True)

{'name': 'world_cup_training_data.csv',
 'asset_type': 'data_asset',
 'asset_id': 'dd88d93f-c0ed-447e-88da-d82c5cee40f2',
 'attachment_id': 'deb4d967-ddb2-4e9a-9908-bed3610f2a65',
 'filepath': 'world_cup_training_data.csv',
 'data_size': 30428614,
 'mime': 'text/csv',
 'summary': ['created or overwritten file',
  'created data asset',
  'created attachment']}

In [28]:
# 1. Calculate the squad value and add it as a new column to the existing dataframe
# This ensures every row (player) now knows the total value of their national team
players_merged_values['squad_total_value'] = players_merged_values.groupby('citizenship')['value'].transform('sum')

# 2. Sort the entire dataframe by this new squad value
# This keeps all players from the same country together, starting with the most valuable nations
power_ranking = players_merged_values.sort_values(by=['squad_total_value', 'value'], ascending=False)

# 3. Format the values to Millions for readability
power_ranking['squad_total_value_m'] = power_ranking['squad_total_value'] / 1_000_000
power_ranking['player_value_m'] = power_ranking['value'] / 1_000_000

# Display the result - you will see all original columns + the new ranking columns
print(power_ranking.head(10))

       player_id       player_slug                player_name  \
68653     683840             pedri             Pedri (683840)
43548     357565             rodri             Rodri (357565)
90289     962110       pau-cubarsi       Pau Cubarsí (962110)
39136     293385         dani-olmo         Dani Olmo (293385)
47922     423440  martin-zubimendi  Martín Zubimendi (423440)
61121     571020      oihan-sancet      Oihan Sancet (571020)
67053     636688   alejandro-balde   Alejandro Balde (636688)
71951     646740              gavi              Gavi (646740)
79613     775605     pablo-barrios     Pablo Barrios (775605)
67068     636703      fermin-lopez      Fermín López (636703)

                                        player_image_url  \
68653  https://img.a.transfermarkt.technology/portrai...
43548  https://img.a.transfermarkt.technology/portrai...
90289  https://img.a.transfermarkt.technology/portrai...
39136  https://img.a.transfermarkt.technology/portrai...
47922  https://img.a.transfermarkt.technology/portrai...
61121  https://img.a.transfermarkt.technology/portrai...
67053  https://img.a.transfermarkt.technology/portrai...
71951  https://img.a.transfermarkt.technology/portrai...
79613  https://img.a.transfermarkt.technology/portrai...
67068  https://img.a.transfermarkt.technology/portrai...

             name_in_home_country date_of_birth              place_of_birth  \
68653        Pedro González López    2002-11-25                    Tegueste
43548  Rodrigo Hernández Cascante    1996-06-22                      Madrid
90289         Pau Cubarsí Paredes    2007-01-22                    Estanyol
39136        Daniel Olmo Carvajal    1998-05-07                    Terrassa
47922     Martín Zubimendi Ibáñez    1999-02-02      Donostia-San Sebastián
61121         Oihan Sancet Tirapu    2000-04-25                    Pamplona
67053    Alejandro Balde Martínez    2003-10-18                   Barcelona
71951    Pablo Martín Páez Gavira    2004-08-05  Los Palacios y Villafranca
79613         Pablo Barrios Rivas    2003-06-15                      Madrid
67068          Fermín López Marín    2003-05-11                 El Campillo

      country_of_birth  height citizenship  ...  third_club_name  \
68653            Spain   174.0       Spain  ...              NaN
43548            Spain   191.0       Spain  ...              NaN
90289            Spain   184.0       Spain  ...              NaN
39136            Spain   179.0       Spain  ...              NaN
47922            Spain   181.0       Spain  ...              NaN
61121            Spain   188.0       Spain  ...              NaN
67053            Spain   177.0       Spain  ...              NaN
71951            Spain   173.0       Spain  ...              NaN
79613            Spain   181.0       Spain  ...              NaN
67068            Spain   174.0       Spain  ...              NaN

      fourth_club_url fourth_club_name date_of_death   date_unix        value  \
68653             NaN              NaN           NaN  2025-06-08  140000000.0
43548             NaN              NaN           NaN  2025-05-29  110000000.0
90289             NaN              NaN           NaN  2025-06-08   80000000.0
39136             NaN              NaN           NaN  2025-06-08   60000000.0
47922             NaN              NaN           NaN  2025-06-08   60000000.0
61121             NaN              NaN           NaN  2025-06-08   60000000.0
67053             NaN              NaN           NaN  2025-06-08   60000000.0
71951             NaN              NaN           NaN  2025-06-08   60000000.0
79613             NaN              NaN           NaN  2025-06-08   55000000.0
67068             NaN              NaN           NaN  2025-06-08   50000000.0

      age squad_total_value squad_total_value_m player_value_m
68653  23      3.731125e+09            3731.125          140.0
43548  29      3.731125e+09            3731.125          110.0
90289  19      3.731125e+09            3731.125           80.0
39136  27      3.731125e+09            3731.125           60.0
47922  27      3.731125e+09            3731.125           60.0
61121  25      3.731125e+09            3731.125           60.0
67053  22      3.731125e+09            3731.125           60.0
71951  21      3.731125e+09            3731.125           60.0
79613  22      3.731125e+09            3731.125           55.0
67068  22      3.731125e+09            3731.125           50.0

[10 rows x 40 columns]

In [29]:
print(power_ranking.columns.tolist())

['player_id', 'player_slug', 'player_name', 'player_image_url', 'name_in_home_country', 'date_of_birth', 'place_of_birth', 'country_of_birth', 'height', 'citizenship', 'is_eu', 'position', 'main_position', 'foot', 'current_club_id', 'current_club_name', 'joined', 'contract_expires', 'outfitter', 'social_media_url', 'player_agent_id', 'player_agent_name', 'contract_option', 'date_of_last_contract_extension', 'on_loan_from_club_id', 'on_loan_from_club_name', 'contract_there_expires', 'second_club_url', 'second_club_name', 'third_club_url', 'third_club_name', 'fourth_club_url', 'fourth_club_name', 'date_of_death', 'date_unix', 'value', 'age', 'squad_total_value', 'squad_total_value_m', 'player_value_m']

In [30]:
wslib.save_data("power_ranking.csv",power_ranking.to_csv(index=False).encode(), overwrite=True)

{'name': 'power_ranking.csv',
 'asset_type': 'data_asset',
 'asset_id': '476778dc-387a-4402-8dfd-149927f65617',
 'attachment_id': '4ca2364d-7d71-497c-9343-7ea6dd30ce6e',
 'filepath': 'power_ranking.csv',
 'data_size': 30131740,
 'mime': 'text/csv',
 'summary': ['created or overwritten file',
  'created data asset',
  'created attachment']}

In [31]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='LcyS2t8qRdTQ1ket25gYggmKTGFhQ85mspd0bjMLfF3k',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/identity/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.direct.us-south.cloud-object-storage.appdomain.cloud')

bucket = 'sandboxproject-donotdelete-pr-snjjamdlq8h7ju'
object_key = 'results.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

results = pd.read_csv(body)
results.head(10)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
5,1876-03-25,Scotland,Wales,4.0,0.0,Friendly,Glasgow,Scotland,False
6,1877-03-03,England,Scotland,1.0,3.0,Friendly,London,England,False
7,1877-03-05,Wales,Scotland,0.0,2.0,Friendly,Wrexham,Wales,False
8,1878-03-02,Scotland,England,7.0,2.0,Friendly,Glasgow,Scotland,False
9,1878-03-23,Scotland,Wales,9.0,0.0,Friendly,Glasgow,Scotland,False

In [33]:
print(results.columns.tolist())

['date', 'home_team', 'away_team', 'home_score', 'away_score', 'tournament', 'city', 'country', 'neutral']

In [36]:
# 1. Prepare a unique Country-Level lookup from your power_ranking data
# We take the unique 'citizenship' and its 'squad_total_value'
country_lookup = power_ranking[['citizenship', 'squad_total_value']].drop_duplicates()

# 2. First Merge: Attach Home Team Value
df_with_home = pd.merge(
    results, 
    country_lookup, 
    left_on='home_team', 
    right_on='citizenship', 
    how='left'
)

# Rename to distinguish from away team and drop the redundant join key
df_with_home = df_with_home.rename(columns={'squad_total_value': 'home_squad_value'})
df_with_home = df_with_home.drop(columns=['citizenship'])

# 3. Second Merge: Attach Away Team Value
df_final = pd.merge(
    df_with_home, 
    country_lookup, 
    left_on='away_team', 
    right_on='citizenship', 
    how='left'
)

# Rename and cleanup
df_final = df_final.rename(columns={'squad_total_value': 'away_squad_value'})
df_final = df_final.drop(columns=['citizenship'])

# 4. Create the Target Column for AutoAI
def get_result(row):
    if row['home_score'] > row['away_score']: return 'Home Win'
    if row['home_score'] < row['away_score']: return 'Away Win'
    return 'Draw'

df_final['target_result'] = df_final.apply(get_result, axis=1)

# 5. Clean up missing values
# If a country in results.csv wasn't in your Transfermarkt data, set value to 0
df_final[['home_squad_value', 'away_squad_value']] = df_final[['home_squad_value', 'away_squad_value']].fillna(0)

print(df_final[['home_team', 'away_team', 'home_squad_value', 'away_squad_value', 'target_result']].head())

  home_team away_team  home_squad_value  away_squad_value target_result
0  Scotland   England      2.857700e+08      2.383295e+09          Draw
1   England  Scotland      2.383295e+09      2.857700e+08      Home Win
2  Scotland   England      2.857700e+08      2.383295e+09      Home Win
3   England  Scotland      2.383295e+09      2.857700e+08          Draw
4  Scotland   England      2.857700e+08      2.383295e+09      Home Win

In [51]:
# Create the target, then DROP the scores
df_final['target_result'] = df_final.apply(get_result, axis=1)

# Keep only the columns that the model should use to PREDICT
# We exclude the scores because we won't know them in 2026!
features_only = df_final[[
    'home_team', 'away_team', 'tournament', 'neutral', 
    'home_squad_value', 'away_squad_value', 'target_result'
]]

In [52]:
wslib.save_data("match_training_data_clean.csv",features_only.to_csv(index=False).encode(), overwrite=True)

{'name': 'match_training_data_clean.csv',
 'asset_type': 'data_asset',
 'asset_id': '7cbc807b-d90a-4450-bfcf-382798207723',
 'attachment_id': '21b2d857-8013-4e8a-bee9-42eb21bcb136',
 'filepath': 'match_training_data_clean.csv',
 'data_size': 3390176,
 'mime': 'text/csv',
 'summary': ['created or overwritten file',
  'created data asset',
  'created attachment']}

In [61]:
import pandas as pd

# 1. Define the 20 Matchups
matchups = [
    ('United States', 'England'), ('Argentina', 'Mexico'), ('France', 'Japan'), 
    ('Brazil', 'Germany'), ('Canada', 'Morocco'), ('Italy', 'Spain'),
    ('Portugal', 'Netherlands'), ('Belgium', 'Croatia'), ('Uruguay', 'South Korea'),
    ('England', 'France'), ('Argentina', 'Brazil'), ('United States', 'Mexico'),
    ('Germany', 'Italy'), ('Spain', 'Portugal'), ('Senegal', 'Netherlands'),
    ('Japan', 'Spain'), ('Denmark', 'Tunisia'), ('Switzerland', 'Serbia'),
    ('Poland', 'Saudi Arabia'), ('France', 'Argentina')
]

test_df = pd.DataFrame(matchups, columns=['home_team', 'away_team'])

# 2. Attach Squad Values
test_df = pd.merge(test_df, country_lookup, left_on='home_team', right_on='citizenship', how='left').rename(columns={'squad_total_value': 'home_squad_value'}).drop(columns=['citizenship'])
test_df = pd.merge(test_df, country_lookup, left_on='away_team', right_on='citizenship', how='left').rename(columns={'squad_total_value': 'away_squad_value'}).drop(columns=['citizenship'])

# 3. Add the structural fields
test_df['tournament'] = 'FIFA World Cup'
test_df['neutral'] = 1

# 4. THE FIX: Explicitly re-index to the exact order your model expects
# This creates a NEW dataframe with the columns in the specific sequence
expected_order = [
    "home_team", 
    "away_team", 
    "tournament", 
    "neutral", 
    "home_squad_value", 
    "away_squad_value"
]

test_final = test_df.reindex(columns=expected_order)

# Verification check
print("Final Column Order:", test_final.columns.tolist())
print(test_final.head(1))

print("Test set created with following columns:")
print(test_final.columns.tolist())
print(f"\nExample row:\n{test_final.iloc[0]}")

Final Column Order: ['home_team', 'away_team', 'tournament', 'neutral', 'home_squad_value', 'away_squad_value']
       home_team away_team      tournament  neutral  home_squad_value  \
0  United States   England  FIFA World Cup        1       343495000.0

   away_squad_value
0      2.383295e+09
Test set created with following columns:
['home_team', 'away_team', 'tournament', 'neutral', 'home_squad_value', 'away_squad_value']

Example row:
home_team            United States
away_team                  England
tournament          FIFA World Cup
neutral                          1
home_squad_value       343495000.0
away_squad_value      2383295000.0
Name: 0, dtype: object

In [65]:
# 1. Strip whitespace and force consistent capitalization
power_ranking['citizenship'] = power_ranking['citizenship'].str.strip()
test_final['home_team'] = test_final['home_team'].str.strip()
test_final['away_team'] = test_final['away_team'].str.strip()

# 2. Create a mapping for common mismatches
name_fixes = {
    'USA': 'United States',
    'US': 'United States',
    'South Korea': 'Korea, South',
    'Republic of Korea': 'Korea, South',
    'Uruguaý': 'Uruguay', # Fixes potential encoding issues
    'Oriental Republic of Uruguay': 'Uruguay'
}

# 3. Apply the fixes to both datasets so they align
power_ranking['citizenship'] = power_ranking['citizenship'].replace(name_fixes)
test_final['home_team'] = test_final['home_team'].replace(name_fixes)
test_final['away_team'] = test_final['away_team'].replace(name_fixes)

print(f"Successfully generated {len(test_final)} matchups.")

Successfully generated 20 matchups.

In [66]:
# 6. Save and upload to watsonx for scoring
wslib.save_data("world_cup_test_data.csv",test_final.to_csv(index=False).encode(), overwrite=True)

{'name': 'world_cup_test_data.csv',
 'asset_type': 'data_asset',
 'asset_id': '370e8962-8f02-4547-9481-64bf0ff66773',
 'attachment_id': 'bf6da73d-6f14-4671-87ff-67d990522886',
 'filepath': 'world_cup_test_data.csv',
 'data_size': 1233,
 'mime': 'text/csv',
 'summary': ['looked up asset',
  'selected attachment',
  'overwritten file',
  'updated attachment'],
 'access_count': 7}

In [67]:
print(test_final.columns.tolist())

['home_team', 'away_team', 'tournament', 'neutral', 'home_squad_value', 'away_squad_value']